include: package:syncfusion_flutter_core/analysis_options.yaml

analyzer:
  errors:
    include_file_not_found: ignore
    lines_longer_than_80_chars: ignore
    invalid_dependency: ignore
    avoid_as: ignore
    unnecessary_null_comparison: false